---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Restart promtail
  ansible.builtin.service:
    name: promtail
    state: restarted
  listen: restart promtail
