---
# This file must be encrypted with: ansible-vault encrypt vault.yml
# To edit: ansible-vault edit vault.yml

vault_grafana_admin_password: "dev-change-me"
vault_grafana_secret_key: "dev-secret-key-32chars-change-me!"
