---
- name: Deploy alloy configuration
  ansible.builtin.template:
    src: config.alloy.j2
    dest: "{{ alloy_config_dir }}/config.alloy"
    owner: "{{ alloy_user }}"
    group: "{{ alloy_group }}"
    mode: "0640"
  notify: restart alloy
