---
galaxy_info:
  role_name: alertmanager
  author: ikhtiyor
  description: "Install and configure alertmanager for monitoring stack"
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - jammy
        - focal
dependencies: []
