[prometheus]
staging-prometheus.example.com

[alertmanager]
staging-alertmanager.example.com

[grafana]
staging-grafana.example.com

[blackbox_exporter]
staging-blackbox.example.com

[event_service]
staging-event-service.example.com

[loki]
staging-loki.example.com

[promtail]
staging-prometheus.example.com
staging-event-service.example.com

[monitoring:children]
prometheus
alertmanager
grafana
blackbox_exporter
event_service
loki
promtail
