[prometheus]
mon-node

[alertmanager]
mon-node

[grafana]
mon-node

[blackbox_exporter]
mon-node

[monitoring:children]
prometheus
alertmanager
grafana
blackbox_exporter

[all:vars]
ansible_connection=community.docker.docker
ansible_user=root
