---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: Restart alloy
  ansible.builtin.service:
    name: alloy
    state: restarted
  listen: restart alloy
