[prometheus]
dev-prometheus.example.com

[alertmanager]
dev-alertmanager.example.com

[grafana]
dev-grafana.example.com

[blackbox_exporter]
dev-blackbox.example.com

[event_service]
dev-event-service.example.com

[monitoring:children]
prometheus
alertmanager
grafana
blackbox_exporter
event_service
