
[monitoring]
orangepi ansible_host=100.96.125.99 ansible_user=root

[node_exporter]
orangepi ansible_host=100.96.125.99 ansible_user=root

[blackbox_exporter]
orangepi ansible_host=100.96.125.99 ansible_user=root

[prometheus]
orangepi ansible_host=100.96.125.99 ansible_user=root

[alertmanager]
orangepi ansible_host=100.96.125.99 ansible_user=root

[grafana]
orangepi ansible_host=100.96.125.99 ansible_user=root

[loki]
orangepi ansible_host=100.96.125.99 ansible_user=root

[promtail]
orangepi ansible_host=100.96.125.99 ansible_user=root
