[prometheus]
prometheus.internal

[alertmanager]
alertmanager.internal

[grafana]
grafana.internal

[blackbox_exporter]
blackbox.internal

[event_service]
event-service.internal

[monitoring:children]
prometheus
alertmanager
grafana
blackbox_exporter
event_service
