---
galaxy_info:
  role_name: alloy
  author: ikhtiyor
  description: Install and configure Grafana Alloy log shipping agent
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - jammy
        - focal
dependencies: []
